// DS Academy — static data

const T = {
  bg:"#13111a", bgCard:"#1c1927", bgDeep:"#161320",
  border:"#2a2540", borderHi:"#3d3660",
  text:"#e2dff0", textDim:"#8b87a8", textFade:"#4a4665",
  p1:"#7eb8f7", p2:"#6dd6a0", p3:"#f7c96e", p4:"#c792ea",
  gold:"#f7c96e", warn:"#f28b82", good:"#6dd6a0", info:"#7eb8f7",
};

const sectionProjects = {
  "python-core": [{type:"coding",title:"Data Cleaner Script",desc:"Write a Python script that takes a messy CSV, cleans it (handle nulls, fix types, remove duplicates), and outputs a clean version. No pandas yet — base Python only."},{type:"coding",title:"File Organizer",desc:"Build a script that reads a folder and sorts files into subfolders by extension, date, or size."}],
  "python-ds": [{type:"dataset",title:"Pandas 30-Question Challenge",desc:"Load the NYC Airbnb dataset. Answer 30 progressively harder questions using only Pandas.",url:"https://www.kaggle.com/datasets/dgomonov/new-york-city-airbnb-open-data"},{type:"coding",title:"NumPy Matrix Operations",desc:"Implement matrix multiplication, dot product, and cosine similarity from scratch using NumPy."}],
  "sql": [{type:"dataset",title:"Business KPI Dashboard in SQL",desc:"Using Chinook, write 10 SQL queries answering real business questions. Use CTEs and window functions.",url:"https://github.com/lerocha/chinook-database"},{type:"coding",title:"SQL Murder Mystery",desc:"Solve a detective story entirely using SQL queries.",url:"https://mystery.knightlab.com"}],
  "stats-prob": [{type:"coding",title:"Bayes Spam Filter",desc:"Build a Naive Bayes spam classifier using only Python and probability math. No sklearn."},{type:"coding",title:"Monte Carlo Simulations",desc:"Use random simulation to estimate π, birthday paradox probability, and expected value of a dice game."}],
  "stats-dist": [{type:"coding",title:"Distribution Fitting",desc:"Take 3 real datasets. Plot histogram, identify best-fit distribution, fit with scipy, verify with Q-Q plot."},{type:"coding",title:"CLT Visualizer",desc:"Demonstrate the CLT: sample from non-normal distributions in increasing sample sizes and visualize."}],
  "stats-inf": [{type:"dataset",title:"A/B Test from Scratch",desc:"Calculate test statistic, p-value, and CI using only numpy — no scipy. Then verify with scipy.",url:"https://www.kaggle.com/datasets/zhangluyuan/ab-testing"}],
  "linalg": [{type:"coding",title:"PCA from Scratch",desc:"Implement PCA using NumPy: center data, compute covariance matrix, find eigenvectors, project data."}],
  "ml-core": [
    {type:"coding",title:"End-to-End ML Pipeline",desc:"Load any Kaggle tabular dataset. Run the full pipeline: EDA → split → train RF → evaluate → cross-validate. Document every step in a notebook.",url:"https://www.kaggle.com/datasets/blastchar/telco-customer-churn"},
    {type:"coding",title:"Regression vs Classification Sprint",desc:"Pick two datasets — one regression, one classification. Train Linear/Logistic Regression + Random Forest on each. Compare metrics and explain which model won and why."},
    {type:"coding",title:"Overfit Then Fix",desc:"Deliberately overfit a Decision Tree (no max_depth). Measure the train/test gap. Then fix it using: max_depth, Random Forest, and cross-validation. Document what changed."},
  ],
  "ml-framework": [{type:"coding",title:"Overfit Then Fix",desc:"Deliberately overfit a decision tree. Then apply regularization, cross-validation, early stopping."}],
  "ml-regression": [{type:"coding",title:"Linear Regression from Scratch",desc:"Implement OLS and gradient descent, compare both against sklearn.",url:"https://www.kaggle.com/c/house-prices-advanced-regression-techniques"}],
  "ml-class": [{type:"dataset",title:"Fraud Detection Challenge",desc:"Handle 99.8% class imbalance. Optimize for recall.",url:"https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud"}],
  "ml-unsupervised": [{type:"dataset",title:"Customer Segmentation",desc:"Use KMeans on e-commerce data. Interpret each cluster in business terms.",url:"https://www.kaggle.com/datasets/carrie1/ecommerce-data"}],
  "ml-pipeline": [{type:"coding",title:"Reproducible Pipeline",desc:"Refactor a messy notebook into clean Python modules. One command to run all."}],
  "feature-eng": [{type:"dataset",title:"Kaggle Feature Engineering Sprint",desc:"Enter a Kaggle tabular competition. Spend 3 days ONLY on feature engineering.",url:"https://www.kaggle.com/competitions"}],
  "dl-nn": [{type:"coding",title:"Neural Net from Scratch",desc:"2-layer NN in NumPy only. Forward pass, backprop, gradient descent. Train on MNIST, reach >90%."}],
  "dl-cnn": [{type:"dataset",title:"Transfer Learning Fine-tune",desc:"Fine-tune pretrained ResNet18 on a dataset of your choice.",url:"https://www.kaggle.com/datasets"}],
  "dl-nlp": [{type:"dataset",title:"Fine-tune BERT",desc:"Fine-tune DistilBERT on text classification. Compare vs TF-IDF + Logistic Regression baseline.",url:"https://www.kaggle.com/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews"}],
  "llm": [{type:"coding",title:"Build a RAG System",desc:"Document Q&A: load PDFs, chunk, embed, store in FAISS, retrieve on query, generate answers with LLM."}],
  "mlops": [{type:"coding",title:"Containerize & Deploy",desc:"Wrap your best model in FastAPI, containerize with Docker, deploy to Railway or Render."}],
  "dataviz": [{type:"coding",title:"Remake a Bad Chart",desc:"Find a confusing chart online. Identify what's wrong. Rebuild as clear visualization.",url:"https://www.reddit.com/r/dataisugly/"}],
  "portfolio": [{type:"portfolio",title:"5-Slide Business Deck per Project",desc:"For each project: Problem → Data → Approach → Results → Recommendation. Present as if to a VP."}],
  "int-sql": [{type:"coding",title:"Timed SQL Sprint",desc:"30-minute timer. 3 hard StrataScratch problems, no autocomplete.",url:"https://www.stratascratch.com"}],
  "int-stats": [{type:"coding",title:"Stats Verbal Drill",desc:"Record yourself answering 5 questions out loud: p-values, A/B test design, CLT, Type I/II errors."}],
  "int-ml": [{type:"coding",title:"Algorithm Explainer Cards",desc:"For each algorithm: 150-word explanation covering intuition, assumptions, failure modes, tuning."}],
  "int-case": [{type:"coding",title:"Case Study Mock",desc:"20-minute timer. Design a recommendation system for Netflix out loud. Record yourself."}],
  "networking": [{type:"portfolio",title:"LinkedIn Content Plan",desc:"4 posts over 4 weeks: something learned, a project, a mistake and fix, a concept explained simply."}],
};

const typeColors = {coding:"#7eb8f7",dataset:"#6dd6a0",portfolio:"#c792ea"};
const typeLabels = {coding:"⌨ Coding",dataset:"📈 Dataset",portfolio:"🚀 Portfolio"};

const portfolioProjects = [
  {id:"proj-python",phase:1,type:"coding",difficulty:"Beginner",title:"Data Cleaner & EDA Tool",description:"Build a Python script that takes any messy CSV, cleans it, and outputs a full EDA report.",dataset:{name:"NYC Airbnb Dataset",url:"https://www.kaggle.com/datasets/dgomonov/new-york-city-airbnb-open-data"},steps:["Load CSV with pandas and inspect: shape, dtypes, nulls","Handle missing values: drop or impute with justification","Fix data types (dates, categories, numerics)","Remove duplicates","Generate 10 insights using groupby and aggregations","Plot 5 charts: distributions, correlations, outliers","Export clean CSV and a summary text file"],skills:["Python","Pandas","Matplotlib","File I/O"],portfolioWorthy:false},
  {id:"proj-sql-kpi",phase:1,type:"dataset",difficulty:"Beginner",title:"Business KPI Dashboard in SQL",description:"Answer 10 real business questions using SQL on a real database.",dataset:{name:"Chinook Music Database",url:"https://github.com/lerocha/chinook-database"},steps:["Set up the Chinook database locally","Write queries for: top 10 customers by revenue, monthly sales trend, best-selling genres","Use CTEs for multi-step logic","Use window functions: rank artists by sales, month-over-month growth","Write one query using all of: JOIN, GROUP BY, HAVING, CTE, window function","Export results and write a 1-page business summary"],skills:["SQL","CTEs","Window Functions","Business Thinking"],portfolioWorthy:false},
  {id:"proj-stats",phase:1,type:"coding",difficulty:"Beginner",title:"A/B Test from Scratch",description:"Run a complete A/B test using only NumPy — no scipy shortcuts.",dataset:{name:"A/B Test Dataset",url:"https://www.kaggle.com/datasets/zhangluyuan/ab-testing"},steps:["Load and explore the dataset","Calculate conversion rates for control and treatment","Compute test statistic manually using NumPy","Calculate p-value from scratch","Compute 95% confidence interval manually","Verify all results match scipy output","Write a recommendation memo"],skills:["Statistics","NumPy","Hypothesis Testing","Python"],portfolioWorthy:false},
  {id:"proj-churn",phase:2,type:"portfolio",difficulty:"Beginner",title:"Customer Churn Predictor",description:"Build an end-to-end churn prediction model with full business framing.",dataset:{name:"Telco Customer Churn",url:"https://www.kaggle.com/datasets/blastchar/telco-customer-churn"},steps:["EDA: visualize churn rate by contract type, tenure, and monthly charges","Feature engineering: encode categoricals, create tenure buckets","Train Logistic Regression, Random Forest, XGBoost","Optimize for recall","Calculate ROI of retaining churners","Deploy as a Streamlit app","Write a 5-slide business summary"],skills:["Python","Pandas","sklearn","XGBoost","Streamlit"],portfolioWorthy:true},
  {id:"proj-abtest",phase:2,type:"dataset",difficulty:"Intermediate",title:"A/B Test Full Analysis",description:"Analyze a real A/B test end-to-end. Go beyond the p-value.",dataset:{name:"A/B Test Dataset",url:"https://www.kaggle.com/datasets/zhangluyuan/ab-testing"},steps:["Calculate conversion rates for control vs treatment","Check sample size — was the test adequately powered?","Run the hypothesis test and compute p-value correctly","Calculate the confidence interval","Discuss practical significance","Write a 1-page recommendation memo to a PM"],skills:["Statistics","Hypothesis Testing","Python","Business Communication"],portfolioWorthy:false},
  {id:"proj-pipeline",phase:2,type:"coding",difficulty:"Intermediate",title:"ML Pipeline from Scratch",description:"Build a complete, reproducible sklearn Pipeline.",dataset:{name:"House Prices Dataset",url:"https://www.kaggle.com/c/house-prices-advanced-regression-techniques"},steps:["Write a data loading module","Build a sklearn ColumnTransformer","Wrap everything in a Pipeline: preprocessor + model","Use GridSearchCV for tuning","Evaluate with cross-validation","Save the pipeline with joblib","Write a predict.py script"],skills:["sklearn Pipelines","Feature Engineering","Clean Code","joblib"],portfolioWorthy:false},
  {id:"proj-nn",phase:3,type:"coding",difficulty:"Intermediate",title:"Neural Network from Scratch (NumPy)",description:"Build a 2-layer neural network using only NumPy.",dataset:{name:"MNIST digits (via sklearn)",url:"https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_digits.html"},steps:["Initialize weights and biases randomly","Implement forward pass: linear + ReLU + softmax","Implement cross-entropy loss","Implement backpropagation manually","Implement gradient descent update","Train on MNIST, reach >90% accuracy","Plot loss curve over epochs"],skills:["NumPy","Backpropagation","Linear Algebra","Deep Learning Math"],portfolioWorthy:false},
  {id:"proj-bert",phase:3,type:"portfolio",difficulty:"Intermediate",title:"NLP Sentiment Classifier — Fine-tuned BERT",description:"Fine-tune a pretrained BERT model on real domain-specific text.",dataset:{name:"IMDb Movie Reviews",url:"https://www.kaggle.com/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews"},steps:["Load and preprocess dataset using Hugging Face tokenizer","Fine-tune DistilBERT using Hugging Face Trainer API","Evaluate: accuracy, F1, confusion matrix","Wrap model in FastAPI","Deploy to Hugging Face Spaces","Write README explaining model, training, and API usage"],skills:["Hugging Face","BERT","FastAPI","NLP","Deployment"],portfolioWorthy:true},
  {id:"proj-rag",phase:3,type:"portfolio",difficulty:"Advanced",title:"RAG-Powered Document Q&A System",description:"Build a system that lets users ask questions about documents using RAG.",dataset:{name:"Any PDF corpus",url:"https://arxiv.org"},steps:["Load and chunk documents","Embed chunks using an embedding model","Store in FAISS or ChromaDB","On query: embed question, retrieve top-k chunks","Pass context + question to LLM","Add a Streamlit UI","Deploy to Hugging Face Spaces"],skills:["LangChain","Vector Databases","Embeddings","LLMs","Streamlit"],portfolioWorthy:true},
  {id:"proj-mlops",phase:3,type:"portfolio",difficulty:"Advanced",title:"End-to-End Deployed ML System",description:"Make any model production-ready: Docker, FastAPI, experiment tracking, live URL.",dataset:{name:"Use your churn model or any existing model",url:""},steps:["Refactor model into clean Python modules","Track experiments with MLflow","Wrap in FastAPI with input validation","Write unit tests","Containerize with Docker","Deploy to Railway or Render","Add /health endpoint and logging"],skills:["FastAPI","Docker","MLflow","Testing","Cloud Deployment"],portfolioWorthy:true},
  {id:"proj-capstone",phase:4,type:"portfolio",difficulty:"Advanced",title:"Capstone: Domain-Specific DS Project",description:"Your magnum opus. Pick a domain, find a real problem, build a complete solution.",dataset:{name:"Find your own — that's part of the exercise",url:"https://datasetsearch.research.google.com"},steps:["Identify a real unsolved problem in your chosen domain","Find or collect relevant data","Full EDA with domain-specific insights","Feature engineering using domain knowledge","Model selection, training, thorough evaluation","Deploy with Streamlit or Gradio","Write a detailed Medium article","Post on LinkedIn"],skills:["Everything — this is your proof of readiness"],portfolioWorthy:true},
];

const DEFAULT_ROADMAP = [
  {phase:1,title:"Foundations",duration:"Months 1–3",color:"#7eb8f7",sections:[
    {id:"python-core",title:"Python Core",weeks:"Week 1–2",why:"Python is the language of data science. Everything you build will be in Python.",warning:"Don't go deep into advanced Python features. Know enough to write clean, readable code.",goldAdvice:"Every day, open a real dataset from Kaggle and answer 5 questions using code you write yourself.",resources:[{name:"Automate the Boring Stuff with Python",type:"Book (free online)",url:"https://automatetheboringstuff.com"},{name:"Python for Everybody — Coursera",type:"Course (free to audit)",url:"https://www.coursera.org/specializations/python"}],tasks:["Variables, loops, functions","List comprehensions & dictionaries","Classes (basics only), file I/O, error handling","Complete Automate the Boring Stuff Ch. 1–8"]},
    {id:"python-ds",title:"Python for Data Science",weeks:"Week 3–4",why:"NumPy and Pandas are what you'll use 40% of your actual job.",warning:"Most people spend 3 days on NumPy and call it done. Spend a full week.",goldAdvice:"After learning each Pandas method, immediately use it on a real dataset.",resources:[{name:"Pandas documentation",type:"Docs",url:"https://pandas.pydata.org/docs/"},{name:"Kaggle Learn — Pandas",type:"Free mini-course",url:"https://www.kaggle.com/learn/pandas"}],tasks:["NumPy: arrays, indexing, slicing, broadcasting","NumPy: vectorized operations (arrays, not loops)","Pandas: Series, DataFrames, groupby, merge, pivot tables","Pandas: handling nulls, apply, method chaining","Daily EDA on real Kaggle dataset — 5 self-asked questions"]},
    {id:"sql",title:"SQL",weeks:"Week 5–7",why:"SQL is tested before ML in almost every DS interview.",warning:"Window functions are where most people give up. Don't.",goldAdvice:"Solve 2 SQL problems every single morning before you do anything else.",resources:[{name:"Mode Analytics SQL Tutorial",type:"Free tutorial",url:"https://mode.com/sql-tutorial/"},{name:"StrataScratch",type:"DS-specific practice",url:"https://www.stratascratch.com"}],tasks:["SELECT, WHERE, GROUP BY, ORDER BY, HAVING, DISTINCT","CASE WHEN statements","INNER, LEFT, RIGHT, FULL JOINs","Subqueries & CTEs (WITH statements)","Window functions: ROW_NUMBER, RANK, LAG, LEAD, SUM OVER","2 StrataScratch problems every morning — timed"]},
    {id:"stats-prob",title:"Probability",weeks:"Week 5–9 (parallel)",why:"Probability is the mathematical language of uncertainty.",warning:"If you can't explain Bayes theorem with a real example without notes, you don't know it.",goldAdvice:"After each topic, write a 1-paragraph explanation as if talking to someone with no math background.",resources:[{name:"StatQuest with Josh Starmer",type:"YouTube (free, exceptional)",url:"https://www.youtube.com/@statquest"},{name:"Seeing Theory",type:"Free interactive visual",url:"https://seeing-theory.brown.edu"}],tasks:["Events, conditional probability, independence","Bayes theorem — explain with a real example, no notes","Watch StatQuest probability series fully"]},
    {id:"stats-dist",title:"Distributions",weeks:"Week 6–9 (parallel)",why:"Distributions describe how data behaves in the real world.",warning:"Don't just learn the formulas. Learn when each distribution appears in real life.",goldAdvice:"The CLT is the foundation of almost all statistical inference. Learn it so you can explain it three ways.",resources:[{name:"StatQuest distributions playlist",type:"YouTube (free)",url:"https://www.youtube.com/@statquest"}],tasks:["Normal, Binomial, Poisson, Uniform distributions","Central Limit Theorem — know it cold, explain 3 ways","5 real-life examples for each distribution"]},
    {id:"stats-inf",title:"Statistical Inference",weeks:"Week 7–10 (parallel)",why:"A/B testing is 80% of what a DS does at a product company.",warning:"'The probability the null hypothesis is true' is WRONG for p-values.",goldAdvice:"Practice all statistics explanations spoken out loud, not written.",resources:[{name:"StatQuest hypothesis testing",type:"YouTube (free)",url:"https://www.youtube.com/@statquest"}],tasks:["Hypothesis testing — explain to a PM out loud without notes","p-value — correct definition, out loud, without notes","Confidence intervals — what they actually mean","Type I and Type II errors with real examples","Practical vs statistical significance","A/B testing end-to-end: design, run, interpret"]},
    {id:"linalg",title:"Linear Algebra",weeks:"Week 10–11 (parallel)",why:"Linear algebra is the math behind PCA, neural networks, and recommendation systems.",warning:"Don't start with a textbook. Watch 3Blue1Brown's visual series first.",goldAdvice:"A matrix is a transformation of space. Dot products measure similarity.",resources:[{name:"3Blue1Brown — Essence of Linear Algebra",type:"YouTube (free)",url:"https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab"}],tasks:["Vectors, matrices, matrix multiplication — visual intuition","Dot product — what it measures","Eigenvalues and eigenvectors at conceptual level","Watch all of 3Blue1Brown Essence of Linear Algebra"]},
    {id:"cli-git",title:"Command Line & Git",weeks:"Week 1 (do this first!)",why:"Every single DS job requires Git.",warning:"Learn the mental model first: what is a commit, a branch, a remote.",goldAdvice:"Your GitHub profile is your DS resume. Push something every day.",resources:[{name:"The Missing Semester of CS Education",type:"Free MIT course",url:"https://missing.csail.mit.edu"},{name:"Learn Git Branching",type:"Free interactive",url:"https://learngitbranching.js.org"}],tasks:["Navigate folders: cd, ls, mkdir, rm, cp, mv","Run Python scripts from terminal","Virtual environments: python -m venv, activate, pip install","Git init, add, commit, push, pull","Branching: create, switch, merge branches","Write meaningful commit messages","Create a professional GitHub profile with a README","Push every project to GitHub with a proper README"]},
    {id:"jupyter",title:"Jupyter & Dev Environment",weeks:"Week 1–2 (parallel)",why:"Bad notebook habits will slow you down for years.",warning:"Notebooks with cells run out of order are not reproducible.",goldAdvice:"Learn keyboard shortcuts for Jupyter — they save hours.",resources:[{name:"VS Code Python setup",type:"Docs",url:"https://code.visualstudio.com/docs/python/python-tutorial"}],tasks:["Set up VS Code with Python extension","Learn Jupyter keyboard shortcuts (A, B, DD, Shift+Enter, M, Y)","Always restart kernel and run all before sharing","Use markdown cells to document your thinking","Understand the difference between script (.py) and notebook (.ipynb)","Know when to use a notebook vs a script"]},
  ]},
  {phase:2,title:"Machine Learning Essentials",duration:"Months 2–4",color:"#a78bfa",sections:[
    {id:"ml-core",title:"ML Foundations",weeks:"Week 1–3",
     why:"This is the core of every DS job. Every algorithm you learn later builds on these concepts.",
     warning:"Don't skip straight to neural networks. Master the fundamentals first — interviewers will expose gaps.",
     goldAdvice:"Run the full sklearn pipeline on 3 different datasets before moving on. Repetition builds real understanding.",
     resources:[
       {name:"Hands-On ML — Aurélien Géron",type:"Book (the bible)",url:"https://www.oreilly.com/library/view/hands-on-machine-learning/9781492032632/"},
       {name:"StatQuest ML playlist",type:"YouTube (free)",url:"https://www.youtube.com/@statquest"},
     ],
     tasks:[
       "Train/test split — why it exists and the golden rule",
       "Linear Regression: fit, predict, interpret R² and RMSE",
       "Logistic Regression: predict classes, use predict_proba",
       "Decision Trees: splitting, max_depth, why they overfit",
       "Random Forest: how bagging reduces variance, feature importances",
       "Model Evaluation: pick the right metric for the right problem",
       "Overfitting vs underfitting: diagnose from train/test gap",
       "Regularization: Ridge vs Lasso intuitively",
       "Cross-validation: k-fold, why it beats single split",
       "Sklearn Pipeline: chain preprocessing + model, prevent leakage",
     ]},
    {id:"ml-advanced",title:"Advanced ML",weeks:"Week 4–6",
     why:"XGBoost wins most tabular Kaggle competitions. It's in almost every production DS system.",
     warning:"Don't tune hyperparameters manually. Use GridSearchCV or Optuna.",
     goldAdvice:"XGBoost + good feature engineering beats neural networks on most tabular data. Don't jump to deep learning too fast.",
     resources:[
       {name:"XGBoost docs",type:"Docs",url:"https://xgboost.readthedocs.io"},
       {name:"Kaggle Intro to ML",type:"Free micro-course",url:"https://www.kaggle.com/learn/intro-to-machine-learning"},
     ],
     tasks:[
       "Gradient Boosting — intuition: how each tree corrects the last",
       "XGBoost: train, tune n_estimators, max_depth, learning_rate",
       "LightGBM: why it's faster than XGBoost",
       "SHAP values: explain any model's predictions",
       "Hyperparameter tuning with GridSearchCV",
       "Handle class imbalance: class_weight, SMOTE, threshold tuning",
     ]},
  ]},
  {phase:3,title:"Core ML",duration:"Months 3–7",color:"#6dd6a0",sections:[
    {id:"ml-framework",title:"The ML Framework",weeks:"Week 1–2",why:"These concepts apply to every single algorithm.",warning:"Most skipped, most costly to skip.",goldAdvice:"For every model: is this overfitting? How do I know?",resources:[{name:"Hands-On ML — Aurélien Géron",type:"Book (the bible)",url:"https://www.oreilly.com/library/view/hands-on-machine-learning/9781492032632/"},{name:"Andrew Ng ML Specialization",type:"Course (free to audit)",url:"https://www.coursera.org/specializations/machine-learning-introduction"}],tasks:["Train / validation / test split — why each exists","Overfitting vs underfitting — diagnose from learning curves","Bias-variance tradeoff — explain intuitively","Cross-validation: k-fold, stratified k-fold","Regularization L1 and L2 — intuition"]},
    {id:"ml-regression",title:"Supervised — Regression",weeks:"Week 3–4",why:"Linear regression is the foundation.",warning:"Understand what coefficients mean and when the model breaks.",goldAdvice:"For each metric, ask: what business question does this answer?",resources:[{name:"StatQuest regression playlist",type:"YouTube (free)",url:"https://www.youtube.com/@statquest"}],tasks:["Linear regression with math — understand what OLS does","Ridge (L2) and Lasso (L1) regression","Polynomial regression — when to use, overfitting risk","Metrics: MAE, MSE, RMSE, R² — when to prefer each"]},
    {id:"ml-class",title:"Supervised — Classification",weeks:"Week 5–6",why:"Classification is the most common ML task.",warning:"Accuracy is a trap in imbalanced datasets.",goldAdvice:"For every algorithm: how does it work, assumptions, when does it fail, how do you tune it.",resources:[{name:"XGBoost docs",type:"Docs",url:"https://xgboost.readthedocs.io"},{name:"StatQuest Random Forest & XGBoost",type:"YouTube",url:"https://www.youtube.com/@statquest"}],tasks:["Logistic regression — understand log-odds, not just sigmoid","Decision Trees — splitting criteria, depth, pruning","Random Forests — why bagging reduces variance","XGBoost — spend extra time here","Metrics: precision, recall, F1, ROC-AUC","Class imbalance: SMOTE, class weights, threshold tuning"]},
    {id:"ml-unsupervised",title:"Unsupervised Learning",weeks:"Week 7",why:"Clustering and dimensionality reduction are everywhere.",warning:"Understand PCA geometrically.",goldAdvice:"Apply PCA to a real dataset and visualize the explained variance plot.",resources:[{name:"StatQuest PCA",type:"YouTube (free)",url:"https://www.youtube.com/@statquest"}],tasks:["KMeans — algorithm, choosing k (elbow, silhouette)","Hierarchical clustering — dendrograms","PCA — geometric understanding","Explained variance ratio — how to choose n components"]},
    {id:"ml-pipeline",title:"Full ML Pipeline",weeks:"Week 8",why:"This week is where you find out what you actually understand.",warning:"Do this from scratch, no tutorial, real dataset.",goldAdvice:"Spend as much time on interpretation as on training.",resources:[{name:"Kaggle datasets",type:"Free real datasets",url:"https://www.kaggle.com/datasets"}],tasks:["Raw data → cleaning → EDA → feature engineering","Model selection → tuning → evaluation","Feature importance and SHAP values","Build from scratch alone, real dataset","Write up findings as if presenting to a stakeholder"]},
    {id:"feature-eng",title:"Feature Engineering",weeks:"Week 9–10",why:"Good feature engineering beats fancy algorithms.",warning:"Target encoding trap: data leakage.",goldAdvice:"Read winning solution writeups of past Kaggle tabular competitions.",resources:[{name:"Kaggle competition forums",type:"Free (winning solutions)",url:"https://www.kaggle.com/competitions"}],tasks:["Missing data: impute vs drop","Label vs one-hot vs target encoding + their traps","Interaction features and polynomial features","Binning and log transforms","Datetime features: hour, day of week, time since event","Read 3 Kaggle winning solution writeups"]},
    {id:"timeseries",title:"Time Series",weeks:"Week 11–12",why:"Time series comes up in 40% of DS jobs.",warning:"You cannot use future data to predict the past. Always use time-based train/test splits.",goldAdvice:"Master the decomposition first: trend + seasonality + residual.",resources:[{name:"Forecasting: Principles and Practice",type:"Free online book",url:"https://otexts.com/fpp3/"}],tasks:["Time series decomposition: trend, seasonality, residual","Stationarity — ADF test, differencing","ARIMA and SARIMA — intuition and fitting","Prophet by Meta — fast and practical","Time-based train/test split — never random split","Evaluation metrics: MAE, RMSE, MAPE"]},
    {id:"eda-tools",title:"EDA & Model Explainability",weeks:"Week 9–10 (parallel)",why:"Companies want to understand WHY the model predicts what it does.",warning:"Don't just run ydata-profiling and call it EDA.",goldAdvice:"SHAP waterfall plots are a conversation-starter in every interview.",resources:[{name:"SHAP docs",type:"Docs",url:"https://shap.readthedocs.io"}],tasks:["ydata-profiling: generate automated EDA report","SHAP values: global feature importance","SHAP waterfall plot: explain single prediction","Present SHAP results as a business insight, not just a chart"]},
    {id:"api-data",title:"APIs & Real Data Sources",weeks:"Week 10 (parallel)",why:"Real data comes from APIs, not Kaggle CSVs.",warning:"Never hardcode API keys in your code. Use environment variables.",goldAdvice:"Build one project using a real public API.",resources:[{name:"requests library docs",type:"Docs",url:"https://requests.readthedocs.io"}],tasks:["HTTP basics: GET, POST, headers, status codes","requests library: fetch data from any API","Handle pagination and rate limits","Parse JSON responses into Pandas DataFrames","Use environment variables for API keys (.env file)"]},
  ]},
  {phase:4,title:"Modern Skills",duration:"Months 7–12",color:"#f7c96e",sections:[
    {id:"dl-nn",title:"Neural Networks",weeks:"Week 1–2",why:"Deep learning is in 20%+ of DS job postings and growing.",warning:"Don't touch PyTorch yet. Build a NN from scratch in NumPy first.",goldAdvice:"The learning rate is the most important hyperparameter.",resources:[{name:"Andrej Karpathy — Neural Networks: Zero to Hero",type:"YouTube (exceptional)",url:"https://www.youtube.com/playlist?list=PLAqhIrjkxbuWI23v9cThsA9GvCAUhRvKZ"}],tasks:["Backpropagation — understand chain rule intuitively","Activation functions: ReLU, sigmoid, tanh","Batch size, learning rate, epochs","Dropout and batch normalization","Build NN from scratch in NumPy","Rebuild it in PyTorch"]},
    {id:"dl-cnn",title:"CNNs & Transfer Learning",weeks:"Week 3–4",why:"Transfer learning is how 90% of real computer vision work is done.",warning:"Don't get lost in architecture details.",goldAdvice:"Pick a domain and fine-tune on a real dataset from that domain.",resources:[{name:"fast.ai Part 1",type:"Free course",url:"https://course.fast.ai"}],tasks:["Convolutional layers and pooling","How CNNs see images intuitively","Transfer learning — why pretrained weights help","Fine-tune ResNet or EfficientNet on custom data","Data augmentation"]},
    {id:"dl-nlp",title:"NLP & Transformers",weeks:"Week 5–6",why:"NLP is the hottest sub-field.",warning:"You don't need to build a transformer from scratch.",goldAdvice:"Pick NLP or Vision and go deeper in one.",resources:[{name:"Hugging Face NLP course",type:"Free",url:"https://huggingface.co/learn/nlp-course"}],tasks:["Text preprocessing, tokenization, embeddings","Attention mechanism — conceptual understanding","BERT and variants","Hugging Face: load and fine-tune a model","NLP metrics: F1, BLEU, perplexity"]},
    {id:"llm",title:"LLMs & Generative AI",weeks:"Week 7–9",why:"Companies are integrating LLMs into every data product.",warning:"Don't just play with ChatGPT. Build something with LLM APIs.",goldAdvice:"Build one project using an LLM API + real data.",resources:[{name:"LangChain docs",type:"Docs",url:"https://docs.langchain.com"}],tasks:["How LLMs work: transformers, attention, tokenization","Prompt engineering — system prompts, few-shot, chain of thought","RAG — the key pattern","Fine-tuning vs RAG","Build one project: LLM API + real data, keep it live"]},
    {id:"mlops",title:"MLOps",weeks:"Week 10–12",why:"Most candidates can train a model. Almost none can deploy one.",warning:"Most DS candidates are bad at Git. Fix this first.",goldAdvice:"'I built this, you can use it right now at this URL' is a conversation-changer.",resources:[{name:"FastAPI docs",type:"Docs",url:"https://fastapi.tiangolo.com"},{name:"Docker getting started",type:"Docs",url:"https://docs.docker.com/get-started/"}],tasks:["Git: branching, PRs, meaningful commit messages","Docker: containerize your model","FastAPI: serve model as live API","MLflow or W&B: experiment tracking","Deploy to cloud — live public URL"]},
    {id:"streamlit",title:"Streamlit — Deploy ML Apps",weeks:"Week 8 (parallel)",why:"'Here's my live demo' is the most powerful thing you can say in an interview.",warning:"Don't over-engineer your Streamlit app.",goldAdvice:"Every project from Phase 2 onwards should have a Streamlit demo.",resources:[{name:"Streamlit docs",type:"Docs",url:"https://docs.streamlit.io"}],tasks:["Build your first Streamlit app in under 1 hour","Add file upload, sliders, dropdowns, and charts","Deploy to Streamlit Cloud — get a live URL","Wrap your churn model in a Streamlit app"]},
    {id:"cloud",title:"Cloud Basics (AWS/GCP)",weeks:"Week 11–12",why:"Every DS job mentions cloud.",warning:"Don't try to learn all cloud services at once.",goldAdvice:"Get the AWS Free Tier account and actually deploy something.",resources:[{name:"AWS Free Tier",type:"Free account",url:"https://aws.amazon.com/free/"}],tasks:["Set up AWS Free Tier account","S3: upload, download, manage files with boto3","EC2: launch a basic instance, SSH into it","Deploy a FastAPI model to EC2 — get a live URL"]},
    {id:"dataviz",title:"Viz & Storytelling",weeks:"Ongoing (parallel)",why:"Being right means nothing if you can't communicate it.",warning:"Don't confuse pretty charts with storytelling.",goldAdvice:"After every project, make a 5-slide summary as if presenting to a VP.",resources:[{name:"Storytelling with Data",type:"Book",url:"https://www.storytellingwithdata.com/book"}],tasks:["Matplotlib & Seaborn for EDA","Plotly for interactive charts","Tableau or Power BI — learn one","5-slide business summary for every project"]},
  ]},
  {phase:5,title:"Portfolio & Jobs",duration:"Months 12–18",color:"#c792ea",sections:[
    {id:"portfolio",title:"Portfolio Projects",weeks:"Month 12–15",why:"Three exceptional projects beat ten mediocre ones.",warning:"'I trained a model on Titanic' is not a project.",goldAdvice:"Write a Medium article per project.",resources:[{name:"Kaggle Datasets",type:"Free",url:"https://www.kaggle.com/datasets"}],tasks:["Churn prediction with dollar-value business framing","Full A/B test analysis beyond p-value","NLP project on a real domain dataset","Recommendation system deployed as API","LLM-powered tool — keep it live","Each project: clean README, write-up, deployed demo"]},
    {id:"int-sql",title:"Interview Prep — SQL",weeks:"Month 13–16",why:"SQL is the first filter in almost every DS interview.",warning:"Practicing with autocomplete is not the same as interview SQL.",goldAdvice:"StrataScratch has questions from real companies. 50 medium/hard problems minimum.",resources:[{name:"StrataScratch",type:"DS-specific SQL practice",url:"https://www.stratascratch.com"}],tasks:["50 StrataScratch problems — medium and hard","Time yourself — 15 minutes max per problem","Practice without autocomplete","Review every wrong answer"]},
    {id:"int-stats",title:"Interview Prep — Statistics",weeks:"Month 13–16",why:"Statistics is the second major filter in DS interviews.",warning:"Most common mistake: getting p-values wrong.",goldAdvice:"Practice ALL statistics explanations spoken out loud.",resources:[{name:"Ace the Data Science Interview",type:"Book",url:"https://www.acethedatascienceinterview.com"}],tasks:["p-value: correct definition out loud without notes","Design an A/B test for a product out loud","Correlation vs causation with real example","Confidence interval: what it actually means"]},
    {id:"int-ml",title:"Interview Prep — ML Theory",weeks:"Month 13–16",why:"ML theory tests whether you understand your tools or just use them.",warning:"Don't memorize answers.",goldAdvice:"For every algorithm: 2-minute verbal explanation.",resources:[{name:"Ace the Data Science Interview",type:"Book",url:"https://www.acethedatascienceinterview.com"}],tasks:["Explain gradient boosting from scratch — 2 min verbal","How does random forest reduce variance?","Class imbalance: 3 ways to handle it","Regularization: L1 vs L2 intuitively"]},
    {id:"int-case",title:"Interview Prep — Case Studies",weeks:"Month 14–17",why:"Case studies test whether you think like a DS.",warning:"Most candidates jump to the model immediately.",goldAdvice:"Framework: clarify → data → metric → model → limitations.",resources:[{name:"Pramp",type:"Free mock interviews",url:"https://www.pramp.com"}],tasks:["Master the framework: clarify → data → metric → model → limits","Design a recommendation system out loud","Design a fraud detection pipeline out loud","Do mock interviews on Pramp or with a friend"]},
    {id:"networking",title:"Networking",weeks:"Start Month 1 — never stop",why:"Most jobs at good companies are found through referrals.",warning:"Don't send cold 'can you refer me?' messages.",goldAdvice:"Pick a domain you care about. Domain expertise is the shortcut most generalists ignore.",resources:[{name:"DataTalks.Club",type:"Free community & events",url:"https://datatalks.club"}],tasks:["Post on LinkedIn weekly — insights, not 'finished a course'","Attend PyData or DataTalks.Club events","Send 1 specific question to 1 relevant person per week","Start applying Month 9 — first 10 apps are practice"]},
    {id:"kaggle",title:"Kaggle Competitions",weeks:"Month 10–14 (parallel)",why:"A top 30% finish on Kaggle shows you can compete against thousands of real data scientists.",warning:"Don't join a competition just to submit once.",goldAdvice:"Your first competition will be humbling. Focus on learning from the leaderboard.",resources:[{name:"Kaggle competitions",type:"Free",url:"https://www.kaggle.com/competitions"}],tasks:["Complete at least one Getting Started competition","Enter one real competition","Read top 3 solution writeups after competition ends","Aim for top 30% on at least one competition"]},
    {id:"linkedin-profile",title:"LinkedIn Optimization",weeks:"Month 12–13",why:"Recruiters search LinkedIn every day.",warning:"Most DS candidates have terrible LinkedIn profiles.",goldAdvice:"Your headline should include your specialization and 'Open to opportunities'.",resources:[{name:"LinkedIn for Job Seekers",type:"Free guide",url:"https://linkedin.com"}],tasks:["Professional headshot","Headline: include specialization and 'Open to opportunities'","Summary: 3 paragraphs — who you are, what you build, what you want","Add all projects with live demo links","Turn on 'Open to Work'"]},
    {id:"salary-neg",title:"Salary Negotiation",weeks:"Month 16–18",why:"Most people leave 10-20% of their salary on the table.",warning:"Never give the first number.",goldAdvice:"Research salaries on Glassdoor, Levels.fyi before any interview.",resources:[{name:"Levels.fyi",type:"Salary data",url:"https://www.levels.fyi"},{name:"Ten Rules for Negotiating — Haseeb Qureshi",type:"Free article (must read)",url:"https://haseebq.com/my-ten-rules-for-negotiating-a-job-offer/"}],tasks:["Research market salaries for DS roles in your target location","Learn the BATNA concept — know your walk-away number","Practice saying 'I need time to consider' out loud","Never accept on the spot — always ask for 48 hours"]},
  ]},
];

const quotes = [
  {text:"The expert in anything was once a beginner.",author:"Helen Hayes"},
  {text:"Stay with problems longer.",author:"Albert Einstein"},
  {text:"The secret of getting ahead is getting started.",author:"Mark Twain"},
  {text:"Small daily improvements lead to stunning results.",author:"Robin Sharma"},
  {text:"A year from now you'll wish you started today.",author:"Karen Lamb"},
  {text:"Every master was once a disaster.",author:"T. Harv Eker"},
  {text:"An investment in knowledge pays the best interest.",author:"Benjamin Franklin"},
];

function getTotalProgress(progress,roadmap){
  const allKeys=roadmap.flatMap(ph=>ph.sections.flatMap(s=>s.tasks.map((_,i)=>`${s.id}-${i}`)));
  const done=allKeys.filter(k=>progress[k]).length;
  return{done,total:allKeys.length,pct:allKeys.length?Math.round(done/allKeys.length*100):0};
}

export { sectionProjects, typeColors, typeLabels, portfolioProjects, DEFAULT_ROADMAP, quotes, getTotalProgress };
